# version: "2"
# services:
#   web:
#     build: .
#     ports:
#       — "8080:8080"
#     depends_on:
#       — mongo
#   mongo:
#     image: mongo
#     ports:
#       — "27017:27017"


version: "2"
services:
  web:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"